### ISSUE TITLE
Missing license file ok

### ISSUE THREAD

**Issue by jnnnthnn** [macintoshpie/this-is-a-really-long-repo-name-ok#3]
hi @macintoshpie 

i'd really like to contribute to this repository

however, the lack of LICENSE file makes me weary about what might be done with my code (e.g. i wouldn't want my long names to be used by a malicious organization with a very short term)

could you please add a LICENSE file?

edit: ok

**Comment by gburtini** [comment]
you forgot to say ok ok

**Comment by macintoshpie** [comment]
hi @jnnnthnn 

thanks for wanting to contribute to this repository.
about the LICENSE file, we decided not to include one. this way, we have more flexibility to potentially abuse the long names you contribute now and forever long

cheers! ok
